name: Your_Proj_name + _test


services:

  db:
    extends:
      file: ../base/db.yaml
      service: db_test


  test:
    extends:
      file: ../base/backend.yaml
      service: backend_test

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    env_file:
      - ../../.env
