"""migration №1

Revision ID: ba14405c30ea
Revises:
Create Date: 2025-04-08 10:55:13.695282

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba14405c30ea"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log",
        sa.Column("client_info", sa.String(), nullable=False),
        sa.Column("secret_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event", sa.Enum("created", "read", "deleted", name="event"), nullable=False
        ),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_log")),
    )
    op.create_table(
        "secret",
        sa.Column("secret", sa.String(), nullable=False),
        sa.Column("passphrase", sa.String(), nullable=True),
        sa.Column("ttl_seconds", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_secret")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("secret")
    op.drop_table("log")
    # ### end Alembic commands ###
